version: '3' 

services: 
  redis: 
    image: "redis:alpine" 
  nprobe: 
    image: "ntopng_docker:latest" 
    command: ['nprobe', '--interface', 'none', '--collector', 'none', '--collector-port', '2055', '--zmq', 'tcp://*:1234'] 
    ports:
     - "2055:2055/udp" 
  ntopng: 
    image: "ntopng_docker:latest" 
    command: ["ntopng", "--redis", "redis", "--interface", "tcp://nprobe:1234", "--local-networks", "192.168.1.0/24"] 
    ports:
     - "8100:3000"
    volumes:
     - "/srv/docker/ntopng/config:/etc/ntopng"
     - "/srv/docker/ntopng/data:/var/lib/ntopng" 
    depends_on: 
     - nprobe
     - redis
